version: "3"
services:
  directus:
    container_name: directus
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 8055:80
    networks:
      - directus
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      PORT: ${PORT}
      PUBLIC_URL: ${PUBLIC_URL}

      # DB
      DB_CLIENT: ${DB_CLIENT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      CONFIG_PATH: "/var/directus/config.js"

      # Cache
      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_TTL: ${CACHE_TTL}

      # Admin
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # S3 image storage
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_ROOT: ${STORAGE_S3_ROOT}

      # SSO
      AUTH_PROVIDERS: ${AUTH_PROVIDERS}
      AUTH_MICROSOFT_DRIVER: ${AUTH_MICROSOFT_DRIVER}
      AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      AUTH_MICROSOFT_SCOPE: ${AUTH_MICROSOFT_SCOPE}
      AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL: ${AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL}
      AUTH_MICROSOFT_IDENTIFIER_KEY: ${AUTH_MICROSOFT_IDENTIFIER_KEY}
      AUTH_MICROSOFT_ICON: ${AUTH_MICROSOFT_ICON}
      AUTH_MICROSOFT_ISSUER_URL: ${AUTH_MICROSOFT_ISSUER_URL}
      AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION: ${AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION}
      AUTH_MICROSOFT_DEFAULT_ROLE_ID: ${AUTH_MICROSOFT_DEFAULT_ROLE_ID}

      # Debug
      # LOG_LEVEL: "trace"
      # LOG_STYLE: "raw"
    healthcheck:
      test: ["CMD-SHELL", curl -f http:localhost/server/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  directus:
