version: "3"
services:
  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - directus
    depends_on:
      - directus
    #command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - directus
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  directus:
    container_name: directus
    restart: unless-stopped
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 8055:80
    networks:
      - directus
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      PORT: ${PORT}
      PUBLIC_URL: ${PUBLIC_URL}

      # DB
      DB_CLIENT: ${DB_CLIENT}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      CONFIG_PATH: "/var/directus/config.js"

      # Cache
      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_TTL: ${CACHE_TTL}

      # Admin
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Azure
      STORAGE_AZURE_DRIVER: ${STORAGE_AZURE_DRIVER}
      STORAGE_AZURE_ACCOUNT_NAME: ${STORAGE_AZURE_ACCOUNT_NAME}
      STORAGE_AZURE_CONTAINER_NAME: ${STORAGE_AZURE_CONTAINER_NAME}
      STORAGE_AZURE_ACCOUNT_KEY: ${STORAGE_AZURE_ACCOUNT_KEY}
      STORAGE_AZURE_ENDPOINT_SUFFIX: ${STORAGE_AZURE_ENDPOINT_SUFFIX}
      STORAGE_AZURE_ROOT: ${STORAGE_AZURE_ROOT}

      # SSO
      AUTH_PROVIDERS: ${AUTH_PROVIDERS}
      AUTH_MICROSOFT_DRIVER: ${AUTH_MICROSOFT_DRIVER}
      AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
      AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
      AUTH_MICROSOFT_SCOPE: ${AUTH_MICROSOFT_SCOPE}
      AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL: ${AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL}
      AUTH_MICROSOFT_IDENTIFIER_KEY: ${AUTH_MICROSOFT_IDENTIFIER_KEY}
      AUTH_MICROSOFT_ICON: ${AUTH_MICROSOFT_ICON}
      AUTH_MICROSOFT_ISSUER_URL: ${AUTH_MICROSOFT_ISSUER_URL}
      AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION: ${AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION}
      AUTH_MICROSOFT_DEFAULT_ROLE_ID: ${AUTH_MICROSOFT_DEFAULT_ROLE_ID}

      # Debug
      # LOG_LEVEL: "trace"
      # LOG_STYLE: "raw"
    healthcheck:
      test: ["CMD-SHELL", curl -f http:localhost/server/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  directus:
